#!/sbin/runscript
# Copyright 1999-2004 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo-x86/www-servers/nginx/files/nginx.init-r2,v 1.1 2010/01/03 19:51:41 djc Exp $

PROGNAME=etcd
PIDPATH=/run/${PROGNAME}
PIDFILE=${PIDPATH}/${PROGNAME}.pid
ETCD_DATA_DIR=/var/lib/${PROGNAME}
LOGPATH=/var/log/${PROGNAME}
USER=etcd

depend() {
	need net
	use dns logger localmount
}

start() {
    if [ ! -d $PIDPATH ] ; then
        mkdir -p $PIDPATH
        chown $USER $PIDPATH
    fi
    if [ ! -d $LOGPATH ] ; then
        mkdir -p $LOGPATH
        chown $USER $LOGPATH
    fi
    if [ ! -d $ETCD_DATA_DIR_DIR ] ; then
        mkdir -p $ETCD_DATA_DIR_DIR
        chown $USER $ETCD_DATA_DIR_DIR
    fi

	ebegin "Starting $PROGNAME"
	start-stop-daemon --start --pidfile $PIDFILE \
		--user $USER --chdir $ETCD_DATA_DIR \
		--background -1 $LOGPATH/$PROGNAME.log -2 $LOGPATH/$PROGNAME.err \
		--ionice 1 --make-pidfile \
		--exec /usr/bin/etcd
	eend $? "Failed to start $PROGNAME"
}

stop() {
	ebegin "Stopping $PROGNAME"
	start-stop-daemon --stop --pidfile $PIDFILE
	eend $? "Failed to stop $PROGNAME"
	rm -f /run/nginx.pid
}

reload() {
	ebegin "Refreshing nginx' configuration"
	kill -HUP `cat $PIDFILE` &>/dev/null
	eend $? "Failed to reload $PROGNAME"
}
